### ISSUE TITLE
trainval_36.h5

### ISSUE THREAD

**Issue by jxn748715A** [BierOne/bottom-up-attention-vqa#8]
Is trainval_36.h5 pre-downloaded, or is it only necessary to pre-download the .tsv file, and trainval_36.h5 is generated through preprocess-image-rcnn.py?

**Comment by BierOne** [comment]
You should first download .tsv files, and then run preprocess-image-rcnn.py. 

trainval_36.h5 will be generated through preprocess-image-rcnn.py

**Comment by jxn748715A** [comment]
However, why do I get the following error when I run preprocess-image-rcnn.py? The other two preprocessing files have already been run successfully. Is it a problem with my file directory? Please help me out. Thank you!

Traceback (most recent call last):
  File "F:\bottom-up-attention-vqa\tools\preprocess-image-rcnn.py", line 75, in <module>
    main()
  File "F:\bottom-up-attention-vqa\tools\preprocess-image-rcnn.py", line 39, in main
    with h5py.File(h5_path, libver='latest') as fd:
  File "E:\anaconda3\envs\py37\lib\site-packages\h5py\_hl\files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "E:\anaconda3\envs\py37\lib\site-packages\h5py\_hl\files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'F:/bottom-up-attention-vqa/data/rcnn/trainval_36.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

![image](https://github.com/BierOne/bottom-up-attention-vqa/assets/77260658/62166079-e561-4b90-be0d-25c933bf1a97)

**Comment by BierOne** [comment]
Could you try the following in the line 39 of preprocess-image-rcnn.py:
> with h5py.File(h5_path, "w", libver='latest') as fd:

Your error just says that the h5 file cannot be opened/created in the given path.

**Comment by jxn748715A** [comment]
ok I have solved this problem thank you very much!

**Comment by BierOne** [comment]
Great : )
